#include <iostream>

int main()
{
    using namespace std;
    cout << "What year was your house built?\n";
    int year;
    cin >> year;

    // The problem is that when cin reads the year, it leaves the newline generated by the Enter key in the input queue.
    // Then cin.getline() reads the newline as an empty line and assigns a null string to the address array.
    cin.get();

    cout << "What is its street address?\n";
    char address[80];
    cin.getline(address, 80);
    cout << "Year built: " << year << endl;
    cout << "Address: " << address << endl;
}